
# #######################################################################################
# My Hyprland Config :3
# #######################################################################################

################
### MONITORS ###
################
source = ~/.config/hypr/hyprland_monitors.conf

###################
### MY PROGRAMS ###
###################
source = ~/.config/hypr/hyprland_programs.conf

#################
### AUTOSTART ###
#################
source = ~/.config/hypr/hyprland_autostart.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################
source = ~/.config/hypr/hyprland_environment.conf

#####################
### LOOK AND FEEL ###
#####################
source = ~/.config/hypr/hyprland_appearance.conf

#############
### INPUT ###
#############
source = ~/.config/hypr/hyprland_input.conf

###################
### KEYBINDINGS ###
###################
source = ~/.config/hypr/hyprland_keybinds.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################
source = ~/.config/hypr/hyprland_windowrulev2.conf
