##################
### WORKSPACES ###
##################
# WORKSPACE 1

# WORKSPACE 2
windowrulev2 = workspace 2, class:^(Spotify)$
windowrulev2 = workspace 2, class:^(vesktop)$

# WORKSPACE 3
windowrulev2 = workspace 3, class:^(Code)$, title:Visual Studio Code

# WORKSPACE 4
windowrulev2 = workspace 4, class:^(steam)$ title:^(Steam)$

####################
### WINDOW RULES ###
####################
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = float,class:^(kitty)$,title:^(kitty)$
windowrule = suppressevent maximize, class:.*
windowrule = float, class:^(Spotify)$
windowrule = float, class:^(firefox)$
windowrule = float, class:^(vesktop)$

###############
### OPACITY ###
###############
windowrulev2 = opacity 0.85 override, class:^(kitty)$
windowrulev2 = opacity 0.95 override, class:^(lite-xl)$
windowrulev2 = opacity 0.95 override, class:^(Code)$
